<pre><span class=reservedWord>private</span><span class=whitespace> </span><span class=reservedWord>void</span><span class=whitespace> </span><span class=identifier>handlePerson</span><span class=separator>(</span><span class=reservedWord>final</span><span class=whitespace> </span><span class=identifier>Agent</span><span class=whitespace> </span><span class=identifier>a</span><span class=separator>)</span><span class=whitespace> </span><span class=separator>{</span><span class=whitespace>
		</span><span class=reservedWord>switch</span><span class=whitespace> </span><span class=separator>((</span><span class=identifier>Activity</span><span class=separator>)</span><span class=whitespace> </span><span class=identifier>a</span><span class=separator>.</span><span class=identifier>get</span><span class=separator>(</span><span class=identifier>ACTIVITY</span><span class=separator>))</span><span class=whitespace> </span><span class=separator>{</span><span class=whitespace>
		</span><span class=reservedWord>case</span><span class=whitespace> </span><span class=identifier>WAITING</span><span class=operator>:</span><span class=whitespace>
			</span><span class=reservedWord>break</span><span class=separator>;</span><span class=whitespace>

		</span><span class=reservedWord>case</span><span class=whitespace> </span><span class=identifier>WALKING</span><span class=operator>:</span><span class=whitespace>
			</span><span class=identifier>a</span><span class=separator>.</span><span class=identifier>wander</span><span class=separator>();</span><span class=whitespace>
			</span><span class=reservedWord>break</span><span class=separator>;</span><span class=whitespace>
		</span><span class=reservedWord>default</span><span class=operator>:</span><span class=whitespace>
			</span><span class=reservedWord>throw</span><span class=whitespace> </span><span class=reservedWord>new</span><span class=whitespace> </span><span class=identifier>RuntimeException</span><span class=separator>(</span><span class=literal>&quot;Unable to handle activity &quot;</span><span class=whitespace>
					</span><span class=operator>+</span><span class=whitespace> </span><span class=separator>(</span><span class=identifier>Activity</span><span class=separator>)</span><span class=whitespace> </span><span class=identifier>a</span><span class=separator>.</span><span class=identifier>get</span><span class=separator>(</span><span class=identifier>ACTIVITY</span><span class=separator>));</span><span class=whitespace>
</span><span class=separator>}</span><span class=whitespace></pre>