<pre>	</span><span class=identifier>Iterator</span><span class=operator>&lt;</span><span class=identifier>Agent</span><span class=operator>&gt;</span><span class=whitespace> </span><span class=identifier>peopleIt</span><span class=whitespace> </span><span class=operator>=</span><span class=whitespace> </span><span class=identifier>people</span><span class=separator>.</span><span class=identifier>iterator</span><span class=separator>();</span><span class=whitespace>
	</span><span class=identifier>Agent</span><span class=whitespace> </span><span class=identifier>teresa</span><span class=whitespace> </span><span class=operator>=</span><span class=whitespace> </span><span class=identifier>peopleIt</span><span class=separator>.</span><span class=identifier>next</span><span class=separator>();</span><span class=whitespace>
	</span><span class=identifier>Agent</span><span class=whitespace> </span><span class=identifier>pietro</span><span class=whitespace> </span><span class=operator>=</span><span class=whitespace> </span><span class=identifier>peopleIt</span><span class=separator>.</span><span class=identifier>next</span><span class=separator>();</span><span class=whitespace>
	</span><span class=identifier>postman</span><span class=whitespace> </span><span class=operator>=</span><span class=whitespace> </span><span class=identifier>peopleIt</span><span class=separator>.</span><span class=identifier>next</span><span class=separator>();</span><span class=whitespace>
	</span><span class=identifier>Agent</span><span class=whitespace> </span><span class=identifier>isolated</span><span class=whitespace> </span><span class=operator>=</span><span class=whitespace> </span><span class=identifier>peopleIt</span><span class=separator>.</span><span class=identifier>next</span><span class=separator>();</span><span class=whitespace>

	</span><span class=identifier>Iterator</span><span class=operator>&lt;</span><span class=identifier>Place</span><span class=operator>&gt;</span><span class=whitespace> </span><span class=identifier>nowheres</span><span class=whitespace> </span><span class=operator>=</span><span class=whitespace>
			</span><span class=identifier>world</span><span class=separator>.</span><span class=identifier>getPlacesOfType</span><span class=separator>(</span><span class=literal>&quot;Nowhere&quot;</span><span class=separator>).</span><span class=identifier>iterator</span><span class=separator>();</span><span class=whitespace>
	</span><span class=identifier>placeOne</span><span class=whitespace> </span><span class=operator>=</span><span class=whitespace> </span><span class=identifier>nowheres</span><span class=separator>.</span><span class=identifier>next</span><span class=separator>();</span><span class=whitespace>
	</span><span class=identifier>placeTwo</span><span class=whitespace> </span><span class=operator>=</span><span class=whitespace> </span><span class=identifier>nowheres</span><span class=separator>.</span><span class=identifier>next</span><span class=separator>();</span><span class=whitespace></pre>