name: Build
on: [ push ]
jobs:
  maven:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          ## REFACTOR enable running on macOS when Maven downloading will work
#          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.4

      - name: Build an executable package
        run: mvn package
